Repository Aloack/Volit_Site, pull requests merged in 2025-02, with the labels that each got.

#2 Feat: Arrumando rotas
  Arquitetura/Aplicacao.drawio
  Arquitetura/Arquitetura.drawio
  Arquitetura/Git.drawio
  aplicacaoweb/package-lock.json
  aplicacaoweb/package.json
  aplicacaoweb/src/app/app.component.html
  aplicacaoweb/src/app/app.component.ts
  aplicacaoweb/src/app/app.config.ts
  aplicacaoweb/src/app/pages/home/home/home.component.html
  aplicacaoweb/src/app/pages/home/home/home.component.scss
  aplicacaoweb/src/app/pages/home/home/home.component.spec.ts
  aplicacaoweb/src/app/pages/home/home/home.component.ts
  aplicacaoweb/src/app/pages/home/homePages/header/header.component.html
  aplicacaoweb/src/app/pages/home/homePages/header/header.component.scss
  aplicacaoweb/src/app/pages/home/homePages/header/header.component.spec.ts
  aplicacaoweb/src/app/pages/home/homePages/header/header.component.ts
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.scss
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.spec.ts
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.ts
Labels: bug

#3 Feat: padronizando rotas e componente de contato
  aplicacaoweb/angular.json
  aplicacaoweb/src/app/app.config.ts
  aplicacaoweb/src/app/pages/content/contact/contact.component.html
  aplicacaoweb/src/app/pages/content/contact/contact.component.scss
  aplicacaoweb/src/app/pages/content/contact/contact.component.spec.ts
  aplicacaoweb/src/app/pages/content/contact/contact.component.ts
  aplicacaoweb/src/app/pages/home/home/home.component.html
  aplicacaoweb/src/app/pages/home/home/home.component.ts
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.ts
Labels: enhancement

#4 Desenvolvimento
  aplicacaoweb/angular.json
  aplicacaoweb/src/app/app.config.ts
  aplicacaoweb/src/app/pages/content/contact/contact.component.html
  aplicacaoweb/src/app/pages/content/contact/contact.component.scss
  aplicacaoweb/src/app/pages/content/contact/contact.component.spec.ts
  aplicacaoweb/src/app/pages/content/contact/contact.component.ts
  aplicacaoweb/src/app/pages/home/home/home.component.html
  aplicacaoweb/src/app/pages/home/home/home.component.ts
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.ts
Labels: enhancement

#14 Feat:Historia e inicio dos serviços
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.scss
Labels: enhancement

#16 Feat: Criação Footer
  aplicacaoweb/src/app/pages/home/home/home.component.html
  aplicacaoweb/src/app/pages/home/home/home.component.ts
  aplicacaoweb/src/app/pages/home/homePages/footer/footer.component.html
  aplicacaoweb/src/app/pages/home/homePages/footer/footer.component.scss
  aplicacaoweb/src/app/pages/home/homePages/footer/footer.component.spec.ts
  aplicacaoweb/src/app/pages/home/homePages/footer/footer.component.ts
Labels: enhancement

#17 Feat: Criação Sobre nós
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.scss
Labels: enhancement

#19 Feat: Arrumando serviços
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.scss
Labels: enhancement

#20 Arrumando e centralizando a Historia e termino dos serviços
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.scss
Labels: bug, enhancement

#21 Feat: Criação patrocinadores
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.scss
Labels: enhancement

#23 Feat: So falta img
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.scss
Labels: bug, enhancement

#24 Feat: Coloquei as imagens, falta alguns ajustes
  aplicacaoweb/src/app/pages/home/homePages/header/header.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.scss
Labels: enhancement

#25 Feat: primeiros ajustes pos reuniao
  aplicacaoweb/src/app/pages/home/homePages/header/header.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.scss
Labels: enhancement

#26 Feat: Nova imagem logo central- add portal no header
  aplicacaoweb/src/app/pages/home/homePages/footer/footer.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.scss
  aplicacaoweb/src/index.html
Labels: enhancement

#27 Feat: imagem logo central
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.html
Labels: enhancement

#30 Feat:novo serviço falta trocar o icone
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.scss
Labels: enhancement

#31 troca de imagem para o novo serviço
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.html
Labels: enhancement

#32 V1.0.0
  aplicacaoweb/src/app/pages/content/contact/contact.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.html
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.scss
Labels: enhancement

#52 Feat: apontamento botao header
  aplicacaoweb/src/app/pages/home/homePages/header/header.component.html
  aplicacaoweb/src/app/pages/home/homePages/header/header.component.ts
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.html
Labels: enhancement

#56 Feat: Responsividade trabalho
  aplicacaoweb/src/app/pages/home/homePages/home-content/home-content.component.scss
Labels: enhancement
